#!/bin/sh

set -e

SCRIPT_DIR=$( cd -- "$( dirname "$( dirname "$0" )")" > /dev/null 2>&1 && pwd )

OPEN_NVIM=0

for arg in "$@"; do
  shift
  case "$arg" in
  '--open-nvim')
    OPEN_NVIM=1
    ;;
  *)
    set -- "$@" "$arg"
    ;;
  esac
done

mkdir -p "$SCRIPT_DIR/.testenv/config/nvim"
mkdir -p "$SCRIPT_DIR/.testenv/data/nvim"
mkdir -p "$SCRIPT_DIR/.testenv/state/nvim"
mkdir -p "$SCRIPT_DIR/.testenv/run/nvim"
mkdir -p "$SCRIPT_DIR/.testenv/cache/nvim"
PLUGINS="$SCRIPT_DIR/.testenv/data/nvim/site/pack/plugins/start"

if [ ! -e "$PLUGINS/plenary.nvim" ]; then
  git clone --depth=1 https://github.com/nvim-lua/plenary.nvim.git "$PLUGINS/plenary.nvim"
fi
if [ ! -e "$PLUGINS/nvim-treesitter" ]; then
  git clone --depth=1 https://github.com/nvim-treesitter/nvim-treesitter.git "$PLUGINS/nvim-treesitter"
fi

if [ ! -e "$PLUGINS/nvim-dev-container" ]; then
  ln -s "$SCRIPT_DIR/" "$PLUGINS/nvim-dev-container"
fi

(cd "$PLUGINS/plenary.nvim" && git pull)
(cd "$PLUGINS/nvim-treesitter" && git pull)

export XDG_CONFIG_HOME="$SCRIPT_DIR/.testenv/config"
export XDG_DATA_HOME="$SCRIPT_DIR/.testenv/data"
export XDG_STATE_HOME="$SCRIPT_DIR/.testenv/state"
export XDG_RUNTIME_DIR="$SCRIPT_DIR/.testenv/run"
export XDG_CACHE_HOME="$SCRIPT_DIR/.testenv/cache"

if [[ $OPEN_NVIM -eq 1 ]]; then
  nvim -u tests/init.vim
else
  nvim --headless -u tests/init.vim \
  -c "RunTests ${1-tests}"
  echo "Success"
fi
